name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1

      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml

      - name: Run tests with Maven
        run: mvn test --file backend/pom.xml