name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Install libssl1.1 and MongoDB dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove -y mongodb-org mongodb-org-tools mongodb-database-tools
          sudo apt-get install -y libssl1.1
          sudo apt-get install -y mongodb
          if [ ! -f /lib/x86_64-linux-gnu/libcrypto.so ]; then
            sudo ln -s /lib/x86_64-linux-gnu/libcrypto.so.1.1 /lib/x86_64-linux-gnu/libcrypto.so
          fi
      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml